{
    name: "Esencial",
    icon: Users,
    price: "USD 25",
    period: "/ equipo / mes",
    devices: "1 a 15 equipos",
    description: "Protección base sólida para negocios que inician.",
    features: [
      "Antivirus Next-Gen",
      "Monitoreo 24/7",
      "Soporte vía WhatsApp",
      "Protección de emails",
      "Reportes semanales",
    ],
    highlight: true,
    badge: "RECOMENDADO",
    cta: "Elegir Esencial",
  },
  {
    name: "Crecimiento",
    icon: Rocket,
    price: "USD 800",
    period: "/ mes (Flat Fee)",
    devices: "hasta 35 equipos",
    description: "La opción inteligente. Control total y soporte prioritario.",
    features: [
      "Todo lo de Esencial",
      "Soporte Prioritario <2hs",
      "Actualización de Apps",
      "Alertas predictivas IA",
      "Control de productividad",
    ],
    highlight: false,
    cta: "Empezar Ahora",
  },
